<?php
/**
 * @file
 */

/*
 * Implements hook_migrate_api()
 */
function trekker_flatfish_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}

/**
 * Implements of hook_ctools_plugin_api().
 *
 */
function trekker_flatfish_ctools_plugin_api($owner, $api) {
  if ($owner == 'trekker_flatfish' && $api == 'default_trekker_flatfish_configs') {
    return array('version' => 1);
  }
}

/**
 * Implements of hook_ctools_plugin_directory().
 */
function trekker_flatfish_ctools_plugin_directory($module, $type) {
  if ($type =='export_ui') {
    return 'plugins/export_ui';
  }
}

/**
 * Implementation of hook_default_trekker_flatfish_config().
 *
 * Load YAML for db conn info, tables, schema, mappings, etc.
 * 
 */
function trekker_flatfish_default_trekker_flatfish_config() {
  $base = 'sites/all/flatfish_migrations';

  if ($path = libraries_get_path('spyc')) {
    require_once $path . '/spyc.php';
  }

  $settings = Spyc::YAMLLoad($base . '/config.yml');
  $schema = Spyc::YAMLLoad($base . '/schema.yml');

  foreach ($settings['types'] as $type => $values) {
    $config[$type] = (object)array(
      'machine_name' => $type,
      'description' => '',
      'api_version' => 1,
      'disabled' => TRUE,
      'config' => array(
        'driver' => 'mysql',
        'database' => $settings['db'],
        'username' => $settings['db_user'],
        'password' => $settings['db_pass'],
        'host' => isset($settings['db_host']) ? $settings['db_host'] : 'localhost',
        'prefix' => isset($settings['db_prefix']) ? $settings['db_prefix'] : '',
      ));
    // schema for media???
    foreach ($schema['schema'] as $k => $v) {
      $config[$type]->config[$type] = array(
        'machine_name' => $k,
        'fields' => $v['fields'],
        'primary key' => $v['primary key'],
      );
    }
  }
}
