<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_trekk_client_source_schema()
 */
function trekk_client_example_trekk_client_source_schema() {
	$schema = array();
  $schema['trekk_server_example'] = array(
    'name' => 'trekk_server_example',
    'label' => t('Trekk Server Example'),
    'description' => t('Describe the data exposed by Trekk Server Example'),
    'fields' => array(
      'nid' => array(
        'type' => 'int',
        'length' => 11,
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'node_title' => array(
        'type' => 'varchar',
        'length' => 255
      ),
    ),
    'primary key' => array('nid'),
  );
	
	return $schema;
}

/**
 * Example mapping class. Start your mapping by boiler plating this one. Note that extending TrekkClientMapping
 * isn't required, but implementing TrekkClientAggregatorMappingInterface is.
 */
class TrekkServerContentExport extends TrekkClientMapping implements TrekkClientAggregatorMappingInterface {
  /**
   * Call the parent's sleep method.
   */
	public function __sleep() {
    return parent::__sleep();
  }

  /**
   * Provide an info array
   */
	public static function info() {
		return array(
		  'name' => 'Trekk Server content_export to node',
		  'description' => t("An example mapping for use with Trekk Server's content_export"),
		);
	}

  /**
   * Return an array of mapping definitions. Array is keyed by the source field. Mapping definitions
   * pretty much mirror the methods on Migrate's mapping classes. 
   */
	public function getMappings() {
		$mappings = array();
		return $mappings;
  }
}
