; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[trekk][download][type] = ""
projects[trekk][download][url] = ""
projects[trekk][type] = "module"

projects[admin_menu][version] = "3.0-rc3"

projects[ctools][version] = "1.0"

projects[devel][version] = "1.3"

projects[entity][version] = "1.0-rc3"

projects[rules][version] = "2.1"

projects[views][version] = "3.3"


